apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        networkpolicy: allow
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java17
          ports:
            - containerPort: 25565
          startupProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: EULA
              value: "true"
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits: # Hard caps for the resources for this pod. Don't over provision your workloads - start small, and add resources as needed. You can use `kubectl top pod PODNAME` to see real resource consumption.
              cpu: 2
              memory: 4Gi
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc
